version: '3'

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports: 
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo_db:27017/node-restapi-shop
      AUTH_JWT: auth_jwt_secret
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
